### ISSUE TITLE
Setup distribution script for this library

### ISSUE THREAD

**Issue by acolchado** [opentable/gcwebclient-libraries#3]
@kara could you please help me create a simple distribution script for this? 
## Steps to build the distribution files

``` shell
$ npm install
$ bower install
$ gulp build
```

This generates a folder called `dist` at the root.

The contents of that folder are what the distribution package is. If they could be added at the wrote of the destination, it would be perfect.

**Comment by kara** [comment]
- [ ] Script installs and builds
- [ ] Script pushes `dist` folder only to `release` branch
- [ ] Script tags version

**Comment by acolchado** [comment]
Already done
